"""
Test Analysis and Recording Utilities / 测试分析和记录工具

This module provides utilities for analyzing and recording detailed information
during agent testing, including FeatureSE weight extraction, FE bucket tracking,
and comprehensive result analysis.

本模块提供智能体测试期间的分析和记录工具，包括 FeatureSE 权重提取、
FE 分桶跟踪和综合结果分析。

Main Components / 主要组件:
    - FeatureSERecorder: Records FeatureSE attention weights during testing
    - FETracker: Tracks function evaluation usage in buckets
    - TestAnalyzer: Comprehensive analyzer combining all recording functions

Main Functions / 主要函数:
    - extract_featurese_weights: Extract weights from FeatureSE module
    - fe_bucket_id: Map FE usage to bucket index

Author: WCC Project
Date: 2026-03-11
"""

import os
from typing import Dict, List, Tuple, Optional, Any, Callable
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd
import torch


# =============================================================================
# Constants / 常量
# =============================================================================

# Default FE buckets for analysis / 默认 FE 分桶用于分析
DEFAULT_FE_BUCKETS = [
    (0, 1e5), (1e5, 2e5), (2e5, 3e5), (3e5, 4e5), (4e5, 5e5),
    (5e5, 6e5), (6e5, 7e5), (7e5, 8e5), (8e5, 9e5), (9e5, 1e6)
]

# Index of s12 (remaining FEs ratio) in state / s12（剩余FEs比例）在状态中的索引
S12_INDEX = 11

# Default record interval / 默认记录间隔
DEFAULT_RECORD_EVERY = 1


# =============================================================================
# Helper Functions / 辅助函数
# =============================================================================

def fe_bucket_id(fe_used: float, buckets: List[Tuple[float, float]] = DEFAULT_FE_BUCKETS) -> int:
    """
    Map function evaluation usage to bucket index.
    将函数评估使用量映射到分桶索引。

    Args:
        fe_used: Number of function evaluations used / 使用的函数评估次数
        buckets: List of (lower, upper) bucket boundaries / 分桶边界列表

    Returns:
        Bucket index / 分桶索引

    Example:
        >>> fe_bucket_id(50000)  # Returns 0
        >>> fe_bucket_id(150000) # Returns 1
    """
    for i, (lo, hi) in enumerate(buckets):
        if lo <= fe_used < hi:
            return i
    return len(buckets)


@torch.no_grad()
def extract_featurese_weights(
    actor: torch.nn.Module,
    state: torch.Tensor
) -> Dict[str, torch.Tensor]:
    """
    Extract FeatureSE weights from actor network.
    从 Actor 网络中提取 FeatureSE 权重。

    This function extracts the attention weights generated by the FeatureSE
    module, including final weights, feature weights, group weights, and
    group statistics.

    此函数提取 FeatureSE 模块生成的注意力权重，包括最终权重、特征权重、
    组权重和组统计量。

    Args:
        actor: Actor network with FeatureSE module / 带 FeatureSE 模块的 Actor 网络
        state: Current state tensor [B, F] / 当前状态张量

    Returns:
        Dictionary containing:
            - w: Final weights [B, F] / 最终权重
            - g_full: Group weights expanded to features [B, F] / 扩展到特征的组权重
            - f: Feature weights [B, F] / 特征权重
            - g: Group weights [B, G] / 组权重
            - s: Group statistics [B, G] / 组统计量

    Example:
        >>> weights = extract_featurese_weights(agent.actor, state)
        >>> print(weights['w'].shape)  # [B, 16]
    """
    fs = actor.featurese

    # Use compute_weights if available (preferred method) / 如果可用则使用 compute_weights（首选方法）
    if hasattr(fs, "compute_weights"):
        return fs.compute_weights(state)

    # Inline computation (fallback, sync with FeatureSE.forward) / 内联计算（后备方法，与 FeatureSE.forward 同步）
    x = state if state.dtype == torch.float32 else state.float()
    x_ln = fs.ln(x)  # Layer normalization / 层归一化

    # Compute group statistics / 计算组统计量
    stats = []
    for (l, r) in fs.groups:
        stats.append(x_ln[:, l:r].mean(dim=1, keepdim=True))
    s = torch.cat(stats, dim=1)                             # [B, G]
    g = torch.sigmoid(fs.g_fc2(fs.act(fs.g_fc1(s))))        # [B, G]

    # Expand group weights to feature level / 将组权重扩展到特征级别
    g_full_parts = []
    for i, (l, r) in enumerate(fs.groups):
        g_full_parts.append(g[:, i:i+1].repeat(1, r-l))
    g_full = torch.cat(g_full_parts, dim=1)                 # [B, F]

    # Compute feature weights / 计算特征权重
    f = torch.sigmoid(fs.f_fc2(fs.act(fs.f_fc1(x_ln))))     # [B, F]
    w = (1.0 - fs.gate_lambda) + fs.gate_lambda * (g_full * f)

    return {"w": w, "g_full": g_full, "f": f, "g": g, "s": s}


# =============================================================================
# Data Classes / 数据类
# =============================================================================

@dataclass
class TestResult:
    """
    Container for test results.
    测试结果容器。

    Attributes:
        fitness_records: Fitness history for each environment / 每个环境的适应度历史
        actions: Action history for each environment / 每个环境的动作历史
        time_elapsed: Time taken for the test / 测试耗时
        fun_id: Problem function ID / 问题函数 ID
    """
    fitness_records: List[List[float]] = field(default_factory=list)
    actions: List[List[Tuple[int, int]]] = field(default_factory=list)
    time_elapsed: float = 0.0
    fun_id: int = -1

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary / 转换为字典"""
        return {
            "fitness_records": self.fitness_records,
            "actions": self.actions,
            "time_elapsed": self.time_elapsed,
            "fun_id": self.fun_id
        }


@dataclass
class FeatureSERecord:
    """
    Container for FeatureSE weight records.
    FeatureSE 权重记录容器。

    Attributes:
        feature_rows: Per-feature weight records / 每特征权重记录
        group_rows: Per-group weight records / 每组权重记录
    """
    feature_rows: List[Dict[str, Any]] = field(default_factory=list)
    group_rows: List[Dict[str, Any]] = field(default_factory=list)

    def to_dataframes(self) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """
        Convert records to pandas DataFrames.
        将记录转换为 pandas DataFrame。

        Returns:
            Tuple of (feature_df, group_df) / (特征 DataFrame, 组 DataFrame)
        """
        return pd.DataFrame(self.feature_rows), pd.DataFrame(self.group_rows)

    def save(self, output_dir: Path) -> None:
        """
        Save records to CSV files.
        将记录保存到 CSV 文件。

        Args:
            output_dir: Directory to save files / 保存文件的目录
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        feat_df, group_df = self.to_dataframes()

        # Save detailed records / 保存详细记录
        feat_df.to_csv(output_dir / 'featurese_weights.csv', index=False)
        group_df.to_csv(output_dir / 'featurese_groups.csv', index=False)

        # Save aggregated records / 保存聚合记录
        agg_feat = feat_df.groupby(["bucket", "feature"])["w"].mean().reset_index()
        agg_group = group_df.groupby(["bucket", "group"])["g"].mean().reset_index()
        agg_feat.to_csv(output_dir / 'featurese_weights_agg.csv', index=False)
        agg_group.to_csv(output_dir / 'featurese_groups_agg.csv', index=False)


# =============================================================================
# Recorders / 记录器
# =============================================================================

class FeatureSERecorder:
    """
    Records FeatureSE attention weights during testing.
    在测试期间记录 FeatureSE 注意力权重。

    This recorder collects FeatureSE weights at specified intervals during
    agent testing, organizing them by FE buckets for analysis.

    此记录器在智能体测试期间按指定间隔收集 FeatureSE 权重，
    并按 FE 分桶组织以便分析。

    Attributes:
        opts: Configuration options / 配置选项
        buckets: FE bucket boundaries / FE 分桶边界
        record_every: Recording interval / 记录间隔

    Example:
        >>> recorder = FeatureSERecorder(opts)
        >>> recorder.record(actor, state, step, fun_id, env_ids)
        >>> recorder.save(output_dir)
    """

    def __init__(
        self,
        opts,
        buckets: List[Tuple[float, float]] = DEFAULT_FE_BUCKETS,
        record_every: int = DEFAULT_RECORD_EVERY
    ):
        """
        Initialize FeatureSE recorder / 初始化 FeatureSE 记录器

        Args:
            opts: Configuration options / 配置选项
            buckets: FE bucket boundaries / FE 分桶边界
            record_every: Record every N steps / 每 N 步记录一次
        """
        self.opts = opts
        self.buckets = buckets
        self.record_every = record_every
        self.record = FeatureSERecord()

    def should_record(self, step: int) -> bool:
        """Check if should record at this step / 检查此步是否应记录"""
        return step % self.record_every == 0

    def record(
        self,
        actor: torch.nn.Module,
        state: torch.Tensor,
        step: int,
        fun_id: int,
        env_ids: List[int]
    ) -> None:
        """
        Record FeatureSE weights for current state.
        记录当前状态的 FeatureSE 权重。

        Args:
            actor: Actor network / Actor 网络
            state: Current state [B, F] / 当前状态
            step: Current step / 当前步数
            fun_id: Problem function ID / 问题函数 ID
            env_ids: Environment indices / 环境索引
        """
        if not self.should_record(step):
            return

        # Extract weights / 提取权重
        ws = extract_featurese_weights(actor, state)
        w = ws["w"].detach().cpu().numpy()
        f = ws["f"].detach().cpu().numpy()
        g_full = ws["g_full"].detach().cpu().numpy()
        g = ws["g"].detach().cpu().numpy()
        s = ws["s"].detach().cpu().numpy()

        # Infer FEs used from state / 从状态推断使用的 FEs
        s12 = state[:, S12_INDEX].detach().cpu().numpy()
        fe_used = self.opts.max_fes * (1.0 - s12)
        buckets = np.array([fe_bucket_id(u, self.buckets) for u in fe_used], dtype=np.int64)

        B, F = w.shape
        G = g.shape[1]

        # Record feature-level weights / 记录特征级权重
        for b_idx, env_id in enumerate(env_ids):
            for j in range(F):
                self.record.feature_rows.append({
                    "fun_id": int(fun_id),
                    "step": int(step),
                    "env": int(env_id),
                    "bucket": int(buckets[b_idx]),
                    "fe_used": float(fe_used[b_idx]),
                    "feature": int(j),
                    "w": float(w[b_idx, j]),
                    "f": float(f[b_idx, j]),
                    "g_full": float(g_full[b_idx, j]),
                })

        # Record group-level weights / 记录组级权重
        for b_idx, env_id in enumerate(env_ids):
            for k in range(G):
                self.record.group_rows.append({
                    "fun_id": int(fun_id),
                    "step": int(step),
                    "env": int(env_id),
                    "bucket": int(buckets[b_idx]),
                    "fe_used": float(fe_used[b_idx]),
                    "group": int(k),
                    "g": float(g[b_idx, k]),
                    "s_mean": float(s[b_idx, k])
                })

    def save(self, output_dir: Path) -> None:
        """Save records to directory / 将记录保存到目录"""
        self.record.save(output_dir)

    def clear(self) -> None:
        """Clear all records / 清除所有记录"""
        self.record = FeatureSERecord()


class TestRecorder:
    """
    Records basic test results (fitness and actions).
    记录基本测试结果（适应度和动作）。

    Attributes:
        n_envs: Number of parallel environments / 并行环境数量
        fun_id: Problem function ID / 问题函数 ID
    """

    def __init__(self, n_envs: int, fun_id: int = -1):
        """
        Initialize test recorder / 初始化测试记录器

        Args:
            n_envs: Number of parallel environments / 并行环境数量
            fun_id: Problem function ID / 问题函数 ID
        """
        self.n_envs = n_envs
        self.fun_id = fun_id
        self.fitness_records = [[] for _ in range(n_envs)]
        self.actions_record = [[] for _ in range(n_envs)]
        self.time_start = 0.0
        self.time_end = 0.0

    def start_timer(self) -> None:
        """Start timing / 开始计时"""
        import time
        self.time_start = time.time()

    def stop_timer(self) -> None:
        """Stop timing / 停止计时"""
        import time
        self.time_end = time.time()

    def record_fitness(self, env_id: int, fitness_list: List[float]) -> None:
        """Record fitness for an environment / 记录环境的适应度"""
        self.fitness_records[env_id].extend(fitness_list)

    def record_action(self, env_id: int, action: Tuple[int, int]) -> None:
        """Record action for an environment / 记录环境的动作"""
        self.actions_record[env_id].append(action)

    def get_result(self) -> TestResult:
        """Get test result / 获取测试结果"""
        return TestResult(
            fitness_records=self.fitness_records,
            actions=self.actions_record,
            time_elapsed=self.time_end - self.time_start,
            fun_id=self.fun_id
        )


# =============================================================================
# Comprehensive Analyzer / 综合分析器
# =============================================================================

class TestAnalyzer:
    """
    Comprehensive test analyzer combining multiple recording functions.
    综合测试分析器，组合多种记录功能。

    This analyzer provides a unified interface for recording:
    - Basic test results (fitness, actions)
    - FeatureSE weights
    - Time tracking

    该分析器提供统一接口用于记录：
    - 基本测试结果（适应度、动作）
    - FeatureSE 权重
    - 时间跟踪

    Example:
        >>> analyzer = TestAnalyzer(opts)
        >>> analyzer.start_test(fun_id, n_envs)
        >>>
        >>> while not done:
        >>>     # ... agent interaction ...
        >>>     analyzer.record_step(actor, state, step, rewards, is_end, info)
        >>>
        >>> result = analyzer.end_test()
        >>> analyzer.save_results(output_dir)
    """

    def __init__(
        self,
        opts,
        enable_featurese: bool = True,
        buckets: List[Tuple[float, float]] = DEFAULT_FE_BUCKETS,
        record_every: int = DEFAULT_RECORD_EVERY
    ):
        """
        Initialize test analyzer / 初始化测试分析器

        Args:
            opts: Configuration options / 配置选项
            enable_featurese: Whether to record FeatureSE weights / 是否记录 FeatureSE 权重
            buckets: FE bucket boundaries / FE 分桶边界
            record_every: Recording interval / 记录间隔
        """
        self.opts = opts
        self.enable_featurese = enable_featurese
        self.test_recorder: Optional[TestRecorder] = None
        self.featurese_recorder: Optional[FeatureSERecorder] = None

        if enable_featurese:
            self.featurese_recorder = FeatureSERecorder(opts, buckets, record_every)

    def start_test(self, fun_id: int, n_envs: int) -> None:
        """
        Start a new test session.
        开始新的测试会话。

        Args:
            fun_id: Problem function ID / 问题函数 ID
            n_envs: Number of environments / 环境数量
        """
        self.test_recorder = TestRecorder(n_envs, fun_id)
        self.test_recorder.start_timer()
        if self.featurese_recorder:
            self.featurese_recorder.clear()

    def record_step(
        self,
        actor: torch.nn.Module,
        state: torch.Tensor,
        step: int,
        actions: torch.Tensor,
        rewards: List,
        is_end: List[bool],
        info: List[Dict]
    ) -> None:
        """
        Record information for one step.
        记录一步的信息。

        Args:
            actor: Actor network / Actor 网络
            state: Current state / 当前状态
            step: Current step / 当前步数
            actions: Actions taken / 采取的动作
            rewards: Rewards received / 收到的奖励
            is_end: Episode termination flags / 回合终止标志
            info: Environment info / 环境信息
        """
        if self.test_recorder is None:
            raise RuntimeError("Must call start_test() before record_step()")

        fun_id = self.test_recorder.fun_id
        env_ids = list(range(self.test_recorder.n_envs))

        # Record FeatureSE weights / 记录 FeatureSE 权重
        if self.featurese_recorder:
            self.featurese_recorder.record(actor, state, step, fun_id, env_ids)

        # Record fitness and actions / 记录适应度和动作
        actions_cpu = actions.detach().cpu()
        for i in range(len(env_ids)):
            if not is_end[i]:
                if 'fitness_record' in info[i]:
                    self.test_recorder.record_fitness(i, info[i]['fitness_record'].copy())
            self.test_recorder.record_action(i, tuple(actions_cpu[i].tolist()))

    def end_test(self) -> TestResult:
        """
        End test session and return results.
        结束测试会话并返回结果。

        Returns:
            TestResult object / TestResult 对象
        """
        if self.test_recorder is None:
            raise RuntimeError("Must call start_test() before end_test()")
        self.test_recorder.stop_timer()
        return self.test_recorder.get_result()

    def save_results(self, output_dir: Path) -> None:
        """
        Save all recorded results to directory.
        将所有记录的结果保存到目录。

        Args:
            output_dir: Directory to save results / 保存结果的目录
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        # Save basic results / 保存基本结果
        if self.test_recorder:
            result = self.test_recorder.get_result()
            data = {"WCC": result.fitness_records, 'WCC_time': [result.time_elapsed]}
            actions_df = pd.DataFrame(result.actions_record)
            actions_df.to_csv(output_dir / 'actions.csv', index=False, header=False)

        # Save FeatureSE results / 保存 FeatureSE 结果
        if self.featurese_recorder:
            self.featurese_recorder.save(output_dir)
